In [23]:
import pandas as pd
df=pd.read_excel("RSC.xlsx")
df
del df['Status']
df
del df['unnamed1']
df
df["Gender"]=df['Gender'].str.replace('M','Male')
df
df["Gender"]=df['Gender'].str.replace('F','Female')
df
df["Marital_Status"]=df["Marital_Status"].astype(str)
df["Marital_Status"]=df["Marital_Status"].str.replace('1','Married')
df
df["Marital_Status"]=df["Marital_Status"].str.replace('0','Single')
df
dff=df["Amount"]=df["Amount"].fillna(0)
df.head(10)
dff=df
df

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount
0,1002903,Sanskriti,P00125942,Female,26-35,28,Single,Maharashtra,Western,Healthcare,Auto,1,23952.0
1,1000732,Kartik,P00110942,Female,26-35,35,Married,Andhra Pradesh,Southern,Govt,Auto,3,23934.0
2,1001990,Bindu,P00118542,Female,26-35,35,Married,Uttar Pradesh,Central,Automobile,Auto,3,23924.0
3,1001425,Sudevi,P00237842,Male,0-17,16,Single,Karnataka,Southern,Construction,Auto,2,23912.0
4,1000588,Joni,P00057942,Male,26-35,28,Married,Gujarat,Western,Food Processing,Auto,2,23877.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11246,1000695,Manning,P00296942,Male,18-25,19,Married,Maharashtra,Western,Chemical,Office,4,370.0
11247,1004089,Reichenbach,P00171342,Male,26-35,33,Single,Haryana,Northern,Healthcare,Veterinary,3,367.0
11248,1001209,Oshin,P00201342,Female,36-45,40,Single,Madhya Pradesh,Central,Textile,Office,4,213.0
11249,1004023,Noonan,P00059442,Male,36-45,37,Single,Karnataka,Southern,Agriculture,Office,3,206.0
11250,1002744,Brumley,P00281742,Female,18-25,19,Single,Maharashtra,Western,Healthcare,Office,3,188.0

In [24]:
dff["Cust_name"].nunique()

1250

In [30]:
#sum of orders by occupation and add grand total
dff.pivot_table(index="Occupation",
                values="Orders",
             aggfunc="sum",
                margins=True,
                margins_name='Grand Total')

                 Orders
Occupation
Agriculture         722
Automobile         1373
Aviation           3215
Banking            2819
Chemical           1310
Construction       1025
Food Processing    1073
Govt               2155
Healthcare         3455
Hospitality        1746
IT Sector          4010
Lawyer             1344
Media              1596
Retail             1270
Textile             894
Grand Total       28007

In [33]:
#to sort by occupation(a-z)
t=dff.pivot_table(index="Occupation",
                values="Orders",
             aggfunc="sum")
t.sort_values(by=["Occupation"],ascending=True)

                 Orders
Occupation
Agriculture         722
Automobile         1373
Aviation           3215
Banking            2819
Chemical           1310
Construction       1025
Food Processing    1073
Govt               2155
Healthcare         3455
Hospitality        1746
IT Sector          4010
Lawyer             1344
Media              1596
Retail             1270
Textile             894

In [34]:
#to sort by order(h-l)
#to sort by occupation(a-z)
t=dff.pivot_table(index="Occupation",
                values="Orders",
             aggfunc="sum")
t.sort_values(by=["Occupation"],ascending=False)

                 Orders
Occupation
Textile             894
Retail             1270
Media              1596
Lawyer             1344
IT Sector          4010
Hospitality        1746
Healthcare         3455
Govt               2155
Food Processing    1073
Construction       1025
Chemical           1310
Banking            2819
Aviation           3215
Automobile         1373
Agriculture         722

In [36]:
#to sort by occupation(a-z)
t=dff.pivot_table(index="Occupation",
                values="Orders",
             aggfunc="sum")
t.sort_values(by=["Orders"],ascending=False)

                 Orders
Occupation
IT Sector          4010
Healthcare         3455
Aviation           3215
Banking            2819
Govt               2155
Hospitality        1746
Media              1596
Automobile         1373
Lawyer             1344
Chemical           1310
Retail             1270
Food Processing    1073
Construction       1025
Textile             894
Agriculture         722

In [41]:
t=dff.pivot_table(index="Product_Category",
                values="Amount",
             aggfunc="sum")
Q7=t.sort_values(by=["Amount"],ascending=False).head(10)
Q7["%"]=100*Q7['Amount']/Q7['Amount'].sum()
Q7.round(0)

                           Amount     %
Product_Category
Food                   33933884.0  34.0
Clothing & Apparel     16495019.0  16.0
Electronics & Gadgets  15643846.0  16.0
Footwear & Shoes       15575209.0  15.0
Furniture               5440052.0   5.0
Games & Toys            4331694.0   4.0
Sports Products         3635933.0   4.0
Beauty                  1959484.0   2.0
Auto                    1958610.0   2.0
Stationery              1676052.0   2.0

In [42]:
Q8=dff.pivot_table(index=['Gender','Age Group'],
                   values="Orders",
                   aggfunc="sum")
Q8.sort_values(['Gender','Orders'],ascending=False).groupby('Gender').head()

                  Orders
Gender Age Group
Male   26-35        3178
       36-45        1785
       18-25        1389
       51-55         698
       46-50         697
Female 26-35        8220
       36-45        3912
       18-25        3261
       46-50        1682
       51-55        1418

In [47]:
Q10=dff.pivot_table(index =['State'],
                   columns= ['Gender'],
                   values ="Amount",
                   aggfunc ="sum",
                   margins=True,
                margins_name='Grand Total')
Q10.round(0)

Gender                Female        Male  Grand Total
State
Andhra Pradesh     5511220.0   2525927.0    8037147.0
Bihar              2819281.0   1203476.0    4022757.0
Delhi              8264499.0   3339320.0   11603819.0
Gujarat            2832262.0   1113820.0    3946082.0
Haryana            3198296.0   1021879.0    4220175.0
Himachal Pradesh   3163299.0   1800069.0    4963368.0
Jharkhand          1954275.0   1072181.0    3026456.0
Karnataka          9933966.0   3589574.0   13523540.0
Kerala             2644088.0   1250404.0    3894492.0
Madhya Pradesh     5301046.0   2800096.0    8101142.0
Maharashtra       10560976.0   3866567.0   14427543.0
Punjab              950267.0    575533.0    1525800.0
Rajasthan          1243444.0    665965.0    1909409.0
Telangana           703814.0    447676.0    1151490.0
Uttar Pradesh     13662105.0   5712863.0   19374968.0
Uttarakhand        1593018.0    927926.0    2520944.0
Grand Total       74335856.0  31913276.0  106249132.0